### ISSUE TITLE
I am unable to get access token.

### ISSUE THREAD

**Issue by hayageek** [saurabhsahni/php-yahoo-oauth2#1]
Received error: 400 Raw response:{"error_description":"Grant type cannot be null","error":"INVALID_INPUT"} 

Can you try again with the current code. Looks like some change in the yahoo service.

**Comment by Roadirsh** [comment]
I got the same problem...

**Comment by hayageek** [comment]
Use this You can use this code
https://github.com/hayageek/oauth2-yahoo

**Comment by JosephP91** [comment]
Got the same problem :(

**Comment by hayageek** [comment]
did you check https://github.com/hayageek/oauth2-yahoo

**Comment by saurabhsahni** [comment]
This issue was resolved as part of the following commit: https://github.com/saurabhsahni/php-yahoo-oauth2/commit/a762362e860d42373aee3b07c078431e598cdb24
