### ISSUE TITLE
Server 2 Server

### ISSUE THREAD

**Issue by Robomedia** [saurabhsahni/php-yahoo-oauth2#2]
How to use Gemini API from console script ?

**Comment by mstrokin** [comment]
please read this doc:
https://developer.yahoo.com/oauth2/guide/flows_authcode/

**Comment by saurabhsahni** [comment]
If you are asking how to run Gemini API in the future without invoking end user auth every time, you need to store the refresh token and use it to get an access token. See more here: https://developer.yahoo.com/oauth2/guide/flows_authcode/#step-5-exchange-refresh-token-for-new-access-token

**Comment by Robomedia** [comment]
Perfect thx.
